name: aeonfall
description: "AEONFALL - a fully illustrated storyboard roguelite."
publish_to: 'none'
version: 2.2.1+12

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  google_mobile_ads: ^9.1.0
  in_app_purchase: ^3.2.3
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/audio/
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
